import { ArrowLeft } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen">
      <div className="max-w-3xl mx-auto px-6 md:px-12 lg:px-16 py-20 md:py-32">
        {/* Back link */}
        <a
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors duration-150 mb-12"
        >
          <ArrowLeft size={14} strokeWidth={1.5} />
          Back to home
        </a>

        {/* Heading */}
        <p className="font-mono text-xs uppercase tracking-widest text-accent mb-4">
          Legal
        </p>
        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter leading-tight mb-4">
          Privacy Policy
        </h1>
        <p className="text-muted-foreground mb-12">
          Last updated: March 2026
        </p>

        {/* Content */}
        <div className="space-y-10 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              1. Information We Collect
            </h2>
            <p className="mb-3">
              When you use getpaidfast, we collect information necessary to provide our service:
            </p>
            <ul className="list-disc list-inside space-y-1.5 ml-2">
              <li>Account information (name, email address)</li>
              <li>Xero account data (invoices, client names, contact details) accessed via OAuth</li>
              <li>Call recordings, transcripts, and outcomes generated by our AI</li>
              <li>Usage data and analytics to improve the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              2. How We Use Your Information
            </h2>
            <p>
              We use your information solely to provide and improve the getpaidfast service. This includes making AI calls on your behalf, generating transcripts and reports, and communicating with you about your account. We do not sell your data to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              3. Xero Data
            </h2>
            <p>
              We access your Xero data through OAuth with read-only permissions for invoices and contacts. We only import the data necessary to identify overdue invoices and make collection calls. You can revoke access at any time through your Xero account settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              4. Call Recordings
            </h2>
            <p>
              All AI calls are recorded and transcribed for your records. Recordings are stored securely and are accessible only to you through your dashboard. We retain recordings for the duration of your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              5. Data Security
            </h2>
            <p>
              We use industry-standard security measures to protect your data, including encryption in transit and at rest. Access to your data is restricted to authorized personnel only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              6. Your Rights
            </h2>
            <p>
              You can request access to, correction of, or deletion of your personal data at any time by contacting us. Under the New Zealand Privacy Act 2020, you have the right to know what information we hold about you and to request its correction or deletion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground tracking-tight mb-3">
              7. Contact
            </h2>
            <p>
              If you have questions about this privacy policy, contact us at{' '}
              <a href="mailto:hello@getpaidfast.ai" className="text-accent hover:underline">
                hello@getpaidfast.ai
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
